name: CI
on:
  push:
    branches:
      # TODO: Make available to public??
      - master

jobs:
  ci-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Setup Android
        uses: actions/setup-java@v2
        with:
          distrobution: 'zulu'
          java-version: '17'
      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Run CI
        run: make ci

